# Generated by Django 5.0.3 on 2024-03-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='david', max_length=50),
            preserve_default=False,
        ),
    ]
